sonar.organization=kroshu
sonar.projectName=kuka_drivers
sonar.projectKey=kroshu_kuka_drivers

sonar.host.url=https://sonarcloud.io

sonar.modules=kuka_sunrise_fri_driver, kuka_iiqka_eac_driver, controllers

kuka_sunrise_fri_driver.sonar.projectName=kuka_sunrise_fri_driver
kuka_sunrise_fri_driver.sonar.sources=./src, ./include,./launch
kuka_sunrise_fri_driver.sonar.exclusions=**/fri_client_sdk/**
kuka_iiqka_eac_driver.sonar.projectName=kuka_iiqka_eac_driver
kuka_iiqka_eac_driver.sonar.sources=./src, ./include/kuka_iiqka_eac_driver
controllers.sonar.projectName=controllers
controllers.sonar.sources=./fri_configuration_controller, ./fri_state_broadcaster

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.python.version=3
