cartesian_pose_controller:
  ros__parameters:
    joints:
    - dummy_cart_joint/x
    - dummy_cart_joint/y
    - dummy_cart_joint/z
    - dummy_cart_joint/qw
    - dummy_cart_joint/qx
    - dummy_cart_joint/qy
    - dummy_cart_joint/qz


    interface_names:
    - position
