external_torque_broadcaster:
  ros__parameters:
    interfaces:
     - external_torque
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    map_interface_to_joint_state:
      effort: external_torque
    use_local_topics: true
