/publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1"]
    # pos1:
    #   positions: [0.3587, 0.3055, -1.3867, 0.0, -0.4896, -0.3587]
    pos1: 
      positions: [0.0017, -2.096, 1.514, 0.0012, -0.9888, -0.0029]



    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

    check_starting_point: false
