/publisher_joint_impedance_controller:
  ros__parameters:

    controller_name: "joint_group_impedance_controller"

    stiffness_goals: [30, 0, 30, 30, 30, 30]
    damping_goals: [0.7, 0.0, 0.7, 0.7, 0.7, 0.7]

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
