/publisher_joint_impedance_controller:
  ros__parameters:

    controller_name: "joint_impedance_controller"

    stiffness_goals: [30, 0, 30, 30, 30, 30]
    damping_goals: [0.7, 0.0, 0.7, 0.7, 0.7, 0.7]

    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
