/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "FRIMessages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(JointValues, JointValues, AUTO)


PB_BIND(TimeStamp, TimeStamp, AUTO)


PB_BIND(CartesianVector, CartesianVector, AUTO)


PB_BIND(Checksum, Checksum, AUTO)


PB_BIND(QuaternionTransformation, QuaternionTransformation, AUTO)


PB_BIND(FriIOValue, FriIOValue, AUTO)


PB_BIND(RedundancyInformation, RedundancyInformation, AUTO)


PB_BIND(MessageHeader, MessageHeader, AUTO)


PB_BIND(ConnectionInfo, ConnectionInfo, AUTO)


PB_BIND(RobotInfo, RobotInfo, AUTO)


PB_BIND(MessageMonitorData, MessageMonitorData, 2)


PB_BIND(MessageIpoData, MessageIpoData, AUTO)


PB_BIND(MessageCommandData, MessageCommandData, 2)


PB_BIND(MessageEndOf, MessageEndOf, AUTO)


PB_BIND(FRIMonitoringMessage, FRIMonitoringMessage, 2)


PB_BIND(FRICommandMessage, FRICommandMessage, 2)














#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
